### ISSUE TITLE
macOS Support

### ISSUE THREAD

**Issue by omor1** [RiotGames/leaguedirector#1]
A cursory look at the code reveals that League Director is primarily Python and Qt, with relatively few portions that would restrict it to Windows support. These appear to be:

* DLL call in `KeyboardHook` from `leaguedirector/bindings.py`
* Windows Registry manipulation in `leaguedirector/enable.py`
* OpenSSL DLLs (`resources/libeay32.dll` and `resources/ssleay32.dll`)

The OpenSSL problem should be the simplest to fix—I believe that Qt on macOS will use Apple's native SSL library/framework (though I could be wrong about that) and doesn't require using an external OpenSSL installation.

The Windows Registry appears to be used to find the installation of League of Legends in Windows, so that the game executables and configuration can be obtained. I don't think this is necessary on macOS, since installation doesn't work the same—the game is more than likely located at `/Applications/League of Legends.app`, with its resources located in the `LoL` directory within (i.e. in `/Applications/League of Legends.app/Content/LoL/`). I'm not sure if there's a way of finding the installation without asking the user, if it's not in the default location. I _guess_ it's possible to use `system_profiler` to list all applications and then filter it, but that's not robust.

The keyboard hook is more difficult. My understanding is that it hooks into the League of Legends application and logs the key presses from a low level—effectively, it's a keylogger. I'm not quite sure how to do the same on macOS, though there's probably some way of doing so, most likely with root privileges (I suspect that League Director needs to be run with Administrator privileges on Windows—otherwise this seems likely a glaring security hole, if any application can trivially hook into another application's functions and intercept them).

Have I missed anything? Unless the League of Legends application itself doesn't support the Replay API on macOS, I think the above would be the only changes necessary to get it to work.

**Comment by cammm** [comment]
Yep this analysis is correct. I’ll see if I find some time this weekend to have a shot at it.

**Comment by cammm** [comment]
Mac support is checked in to the master branch, if you are interested in helping test it out that would be great. I'll produce a release for download probably sometime next week.
