### ISSUE TITLE
Add change location installer

### ISSUE THREAD

**Issue by Serpic** [RiotGames/leaguedirector#11]
It seems that in the previous version it was possible to change the installation folder, now it simply install the program in D:\Program Files (x86)\, on a non-system disk.

**Comment by cammm** [comment]
No problem, I can add this on the next release.

**Comment by saberhosneydev** [comment]
Weird , it doesn't happen to me , it installed on C drive normally .

**Comment by cammm** [comment]
This was added in version 0.1.1: https://github.com/RiotGames/leaguedirector/releases/latest
