### ISSUE TITLE
Does the program run on a Live server?

### ISSUE THREAD

**Issue by Serpic** [RiotGames/leaguedirector#13]
I heard that program should work on version 9.4 and higher, but in fact (for me), for Live server does not work. Camera rotation function do not work.

**Comment by Ivi104** [comment]
The program should work fine on a replay of a 9.4 game. Start the program, make sure the path in the welcome screen is correct, and the checkbox next to it is checked. Start a replay of a match played on patch 9.4. When the replay loads completely, League Directors interface should change. 

In the replay, change the view to 'FPS Camera', and try moving the view with Numpad keys (you can adjust the specific keys in the replay settings, by pressing Esc - Hotkeys - Camera movement)

If any of that didn't work, please describe in more detail what exactly happened

**Comment by Serpic** [comment]
It turns out everything works, just in the game it was written that you need to push on "/" to turn on the camera from the first person, so I clicked... on numpad. After that, the key has changed to "." and everything began to work.
