### ISSUE TITLE
Manually Adding Directories

### ISSUE THREAD

**Issue by Hudki** [RiotGames/leaguedirector#15]
Is it possible on the 'Ready To Connect' to allow users to manually add their League directories. Would be useful for people who saved previous versions of the folder to access old league files.

**Comment by RiotTuxedo** [comment]
The "Ready To Connect" window is a formality. The purpose of this window is to enable a config option to enable the Replay API in the game client. You can manually enable this config option and when the game client starts, League Director should just connect to the game client automatically.

You can see [here](https://github.com/RiotGames/leaguedirector/blob/2089b2618f751f5c281c44e2b74e65963d9d3ae5/leaguedirector/app.py#L739), the window adds a list of game clients that listen for an `itemChanged` event. The item change event triggers the `setGameEnabled` on click. You can find the method definition [here](https://github.com/RiotGames/leaguedirector/blob/662e087abdf4a4d187f1b59d1b2573b265d21d6d/leaguedirector/enable.py#L83). It just adds `EnableReplayApi=1` to `Game.cfg` under the `[General]` category. Example:

C:\Riot Games\League of Legends\Config\Game.cfg
```
[General]
...
EnableReplayApi=1
```

**Comment by Hudki** [comment]
> The "Ready To Connect" window is a formality. The purpose of this window is to enable a config option to enable the Replay API in the game client. You can manually enable this config option and when the game client starts, League Director should just connect to the game client automatically. You can read more about this here: https://developer.riotgames.com/replay-apis.html
> 
> You can see [here](https://github.com/RiotGames/leaguedirector/blob/2089b2618f751f5c281c44e2b74e65963d9d3ae5/leaguedirector/app.py#L739), the window contains a list of game client items that listen for an `itemChanged` event. The item change event triggers the `setGameEnabled` on click. You can find the method definition [here](https://github.com/RiotGames/leaguedirector/blob/662e087abdf4a4d187f1b59d1b2573b265d21d6d/leaguedirector/enable.py#L83). It just adds `EnableReplayApi=1` to `Game.cfg` under the `[General]` category. Example:
> 
> C:\Riot Games\League of Legends\Config\Game.cfg
> 
> ```
> [General]
> ...
> EnableReplayApi=1
> ```

Well more like it in the means of viewing .rofl files in older patches... 
Example of something like copying a 8.23 League folder and saving a .rofl replay file under \deploy. SkinSpotLight supports this as it has an option to select if user is viewing an older patch, however League Director doesn't detect if using a seperate League folder. Hence, why I was wondering if there was a way to select a different directory in the case where it's looking for the "League of Legends.exe" from the process.

**Comment by cammm** [comment]
I understand what you are doing, and it is probably easy enough for you to fix this by just making sure your old copies of the game all have EnableReplayApi=1 set in their game.cfg files.

It does not matter if league director does not find your old copies of the game in the welcome screen, as it will automatically connect regardless once the replay starts up provided you have configured the api on.

Note that the API is only available from patch 9.4 onwards so older version of the game won't work at all.

**Comment by Hudki** [comment]
> I understand what you are doing, and it is probably easy enough for you to fix this by just making sure your old copies of the game all have EnableReplayApi=1 set in their game.cfg files.
> 
> It does not matter if league director does not find your old copies of the game in the welcome screen, as it will automatically connect regardless once the replay starts up provided you have configured the api on.
> 
> Note that the API is only available from patch 9.4 onwards so older version of the game won't work at all.

Ah got it. thanks for the clarification!

**Comment by cammm** [comment]
Latest version has better detection of game clients, provided you have launched the game before it should find it. Let me know if this is not the case (and where you have copied the game install to).

https://github.com/RiotGames/leaguedirector/releases/latest
