### ISSUE TITLE
Doesn't work with Garena servers

### ISSUE THREAD

**Issue by spankhead** [RiotGames/leaguedirector#19]
When I started the application, there is no checkbox(es) in the area which are supposed to have some of them. And it doesn't work of course.

Even after that I kept the app on and try to start a replay, but to no avail.

A screenshot of the app can be found just below.

![new bitmap image 3](https://user-images.githubusercontent.com/48056507/53491170-478ffe00-3ac8-11e9-962b-3bd4524c9b3b.jpg)

**Comment by AvengerHK** [comment]
It works, you just need to edit the game.cfg manually at
C:\Garena\Games\32775\Game\Config\game.cfg

and add 
EnableReplayApi=1
at the [General] tab

However, it only works on your own replay file.
I wonder if it works on spectator in the future.

**Comment by imkengi** [comment]
![image](https://user-images.githubusercontent.com/48059971/53497733-68138480-3ad7-11e9-8377-dbd51d992fc3.png)
![image](https://user-images.githubusercontent.com/48059971/53497741-6f3a9280-3ad7-11e9-9105-3f02f45400c9.png)
it didn't work

**Comment by hung291099** [comment]
it happened same to me, do you actually how to fix it?

**Comment by spankhead** [comment]
It still won't work.

**Comment by Anewbiewanttoknowmore** [comment]
Neither do I, I doesn't work

**Comment by cammm** [comment]
Latest version 0.1.1 should now work with Garena: https://github.com/RiotGames/leaguedirector/releases/latest
