### ISSUE TITLE
The program crashes

### ISSUE THREAD

**Issue by Serpic** [RiotGames/leaguedirector#2]
If after starting the program to press any key on the keyboard, then it will crash it.

In addition, LeagueDirector for some reason has to be launched again after launching the replay. Yes, the camera rotation function works after first launched, but the program closes itself.

**Comment by cammm** [comment]
Sorry about that, I will publish a new version of league director that includes some more debugging to help us pin down what is going wrong and let you know so you can try it out again.

**Comment by cammm** [comment]
Duplicate of #7
