### ISSUE TITLE
Camera movment problems

### ISSUE THREAD

**Issue by TyxyT** [RiotGames/leaguedirector#20]
I am unable to move the Camera Freely on FPS mode and can't seem to figure out how... Iv'e seen recently people saying that the default key to move the camera is 8,4,5,6 but It doesn't work for me aswell...  pressing AWSD or arrow keys just triggers something else and doesn't move the camera too, Any solution to this maybe?

**Comment by cammm** [comment]
Key bindings for camera movement can be set in the game options screen.

![image](https://user-images.githubusercontent.com/81903/53654036-968d7e80-3c01-11e9-88e0-e675e31b84ba.png)
