### ISSUE TITLE
The skybox does not work 

### ISSUE THREAD

**Issue by Miloqc** [RiotGames/leaguedirector#22]
Hi Everybody I have been using the league Director just for fun but the skybox does not work with my game, I'm from the LAN server and League of legends Support told me to write my experience here, just in any case it can help to fix issues. No matter the skybox I choose the background is always black. 

![league director 1](https://user-images.githubusercontent.com/48102505/53589751-35f93580-3b5e-11e9-85f4-953710264522.jpg)
![league director 2](https://user-images.githubusercontent.com/48102505/53589752-3691cc00-3b5e-11e9-8f68-2cffd75a1348.jpg)
![league director 3](https://user-images.githubusercontent.com/48102505/53589753-3691cc00-3b5e-11e9-9bd6-17e7e4cd729a.jpg)
![league director 4](https://user-images.githubusercontent.com/48102505/53589754-3691cc00-3b5e-11e9-9989-d2acd5dd444f.jpg)

**Comment by RiotTuxedo** [comment]
You need to be on the highest graphic settings and have a relatively new GPU (within the last decade or so).

**Comment by Miloqc** [comment]
> You need to be on the highest graphic settings and have a relatively new GPU (within the last decade or so).

Hi, I have the highest graphic settings, An Intel Core I7, 2GB AsRock grapich card, TUF gaming Mother Board.. Do you think is not enough for the League Director? :C

**Comment by cammm** [comment]
Try setting to the highest and then restarting the replay. The game requires a restart after changing that value.

**Comment by Miloqc** [comment]
Thank you! Now is working! 
![1](https://user-images.githubusercontent.com/48102505/53818696-7d087180-3f36-11e9-9e12-c90e70f7fb75.jpg)



> Try setting to the highest and then restarting the replay. The game requires a restart after changing that value.
