### ISSUE TITLE
Use league director in TR servers, opening replays via shortcut

### ISSUE THREAD

**Issue by oxaciano** [RiotGames/leaguedirector#24]
The league replay tool needs to be launched from the ingame. In my specific case, replays are launched dumping the .rofl into the executable or by creating a shortcut of the excutable. League director does not load when the replays starts.

**Comment by RiotTuxedo** [comment]
League Director should start regardless of whether the replay was started in or out of the client. As long as the game client is running with the Replay API enabled. Can you check your `Config/Game.cfg` file for `EnableReplayApi=1` under `[General]`?

**Comment by oxaciano** [comment]
Yes, this is already done and ready 
![asde](https://user-images.githubusercontent.com/48367845/54057840-c70d8380-41d2-11e9-817f-1d35d3c08005.JPG)
Also, the replay system recognises the client, but does not launch. 
![asdeadas](https://user-images.githubusercontent.com/48367845/54057889-fb813f80-41d2-11e9-8304-bd7f4720d989.JPG)

**Comment by RiotTuxedo** [comment]
Are you playing on a tournament realm? What patch is the replay from?

**Comment by oxaciano** [comment]
Yes. Patch 9.3

**Comment by RiotTuxedo** [comment]
Ah ha, the Replay API is only available on patch 9.4 and after. There's the problem :(

**Comment by oxaciano** [comment]
OH, thank you anyway! :)
