### ISSUE TITLE
Skybox not working for me

### ISSUE THREAD

**Issue by randolll** [RiotGames/leaguedirector#26]
I recently downloaded the League Director tool, I did all the setup steps and when I started to use it, I couldn't use the skybox, the replay only shows me a black sky when I selected another skybox.

Thanks for reading :) 
![black](https://user-images.githubusercontent.com/48397997/54080001-62772500-42b5-11e9-904b-807cd15a437f.png)

**Comment by RiotTuxedo** [comment]
This typically happens if your graphics settings aren't on `Very High`. Once changing this setting you'll need to restart your replay for it to take effect.

**Comment by randolll** [comment]
Thank so much, it worked.

**Comment by randolll** [comment]
Thank you so much. It works!
