### ISSUE TITLE
Timing functions makes the camera go crazy

### ISSUE THREAD

**Issue by theprometeus** [RiotGames/leaguedirector#28]
Some timing functions make the camera go crazy, and some of them just doesn't work.

For example, I'll talk about elastic.
I've tried to use it several times and none of them worked (elasticEaseIn, elasticEaseOut, elasticEaseInOut). It just stops, and the camera goes crazy.

I don't know if this was the proposal of the elastic, but I know the elastic function another way.

But, all other functions give the same bugs too.

Some functions make the camera stops too sudden like it's not smooth.

I think this is something in the client because, even using my own director version (Electron-based, not related to the original one), it gives me the same effect.

https://youtu.be/MNhHfY31RDA

**Comment by cammm** [comment]
Try using the smooth step and smoother step options, elastic is intentionally supposed to shake back forth. You can see this page for a reference on what some of those options should look like: https://easings.net
