### ISSUE TITLE
Doesn't Function

### ISSUE THREAD

**Issue by Brothajiff** [RiotGames/leaguedirector#3]
I launch the program. It does see my client location and PBE location and the boxes next to them are checked. However, once I launch a replay nothing happens. I have tried starting it both before and after starting a replay. I have also tried the same with running as admin. Any thoughts?

**Comment by nekyP** [comment]
same for me

**Comment by cammm** [comment]
We can probably fix whatever is going wrong but I need some help from you guys to help debug it.

Startup a replay on PBE making sure that league director has the checkbox ticked next to where you PBE is installed. Then open the following URL in your browser:

https://127.0.0.1:2999/replay/game

You will need to skip past the security warnings, but then it should return something like this:

`
{
    "processID": 9596
}
`

Let me know if that works for you. You can also come and chat to me in the league of editing discord and we can try a few things out.

https://discord.gg/aXRWmQ

**Comment by Brothajiff** [comment]
I can try this out this afternoon when I am home from work. That discord invite doesn't work for me as well.

**Comment by cammm** [comment]
Sorry try this one: https://discord.gg/7j5fdRp

**Comment by Brothajiff** [comment]
That one worked great thank you. Will be in touch a bit later!

**Comment by Morodar** [comment]
I have a problem running leaguedirector either by using source code or by using the installer of [v0.1](https://github.com/RiotGames/leaguedirector/releases/tag/v0.1).

Leaguedirector opens and does not connect to the game
![python_0ra0rmhayk](https://user-images.githubusercontent.com/10113399/52869872-f0447200-3146-11e9-9dab-d8e7bf79e95a.png)

Output when I run the `run.bat` 
```
Requirement already satisfied: pipenv in c:\python37\lib\site-packages (2018.11.26)
Requirement already satisfied: virtualenv-clone>=0.2.5 in c:\python37\lib\site-packages (from pipenv) (0.5.1)
Requirement already satisfied: setuptools>=36.2.1 in c:\python37\lib\site-packages (from pipenv) (40.6.2)
Requirement already satisfied: pip>=9.0.1 in c:\python37\lib\site-packages (from pipenv) (19.0.2)
Requirement already satisfied: certifi in c:\python37\lib\site-packages (from pipenv) (2018.11.29)
Requirement already satisfied: virtualenv in c:\python37\lib\site-packages (from pipenv) (16.4.0)
Installing dependencies from Pipfile.lock (9a6b12)…
  ================================ 3/3 - 00:00:01
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
qt.network.ssl: QSslSocket: cannot call unresolved function d2i_X509
qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed
qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed
qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed
qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed
qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed
qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed
qt.network.ssl: QSslSocket::c/replay/gameonnectToH ostETLS initialization failedncrypted: TLS
initialization failed
qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed
qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed
...
```

**Comment by leumasme** [comment]
Same here on normal client.

**Comment by cammm** [comment]
League Director only works on PBE right now - but 9.4 is going live this week after which it will work everywhere.

**Comment by 3bada** [comment]
Trying it on EUW now but I have the same issue, it's not connecting to my replays. Maybe it only works if the directory is in C drive?

**Comment by gucioslaw14** [comment]
Well it doesnt work for me but should, right? It;s already on live servers not only PBE right? xd

**Comment by cammm** [comment]
Closing this thread as there are a bunch of things mentioned. If you have a specific issue that you can describe and reproduce feel free to open another issue.
