### ISSUE TITLE
League director not launching 

### ISSUE THREAD

**Issue by oOKairosOo** [RiotGames/leaguedirector#30]
Hey everyone . Just wanna say i love this tool and its totally amazing , i recently made a montage using this tool and i love it  . Its grown on me and everything feels so natural . I recently encountered a problem where i can't launch the app. I double click it and nothing happens . I tried reinstalling , making sure the replay api was enable in league of legends game.cfg file and running as admin. Hope we can reach a conclusion thanks in advance!

**Comment by RiotTuxedo** [comment]
@oOKairosOo do you have any logs for League Director? The logs are saved to `(USER)/Documents/LeagueDirector/logs/`

**Comment by oOKairosOo** [comment]
> @oOKairosOo do you have any logs for League Director? The logs are saved to `(USER)/Documents/LeagueDirector/logs/`

i do i have 20 log files

**Comment by cammm** [comment]
Try renaming your /Documents/LeagueDirector folder to LeagueDirectorBackup and relaunching the program. I think your settings may have become corrupt and so this will clear that out (and reset your settings unfortunately). You can copy your sequences folder back over if this works.

**Comment by oOKairosOo** [comment]
> Try renaming your /Documents/LeagueDirector folder to LeagueDirectorBackup and relaunching the program. I think your settings may have become corrupt and so this will clear that out (and reset your settings unfortunately). You can copy your sequences folder back over if this works.

This is absolutely what happened ! Thank you for your help! Its working perfectly fine now and i can get back to doing awesome stuff . I really appreciate it and thanks again :D
