### ISSUE TITLE
League Director doesn't launch on old replays

### ISSUE THREAD

**Issue by JadenAnjara** [RiotGames/leaguedirector#34]
So I was doing some camera moves with a replay, then I went for some games.
Unfortunately, the game I was replaying became my 21st recent game so it came out of the Match History. So I took the ROFL file and dragged it on the LoL.exe to make it work and I got the replay.
But I noticed that League Director didn't detect it and still was on the "choose folder" startup window and my in game settings (mouse speed, camera speed, sound volume...) were totally reset to default

**Comment by cammm** [comment]
Is the old version at least version 9.4? The API went live in that release.

You should also follow the instructions here to make sure the old copy of your LOL installation has the correct config: https://developer.riotgames.com/replay-apis.html

**Comment by JadenAnjara** [comment]
Yes it is, I will check those instructions. Thanks for your help!
