### ISSUE TITLE
Checkbox is blank

### ISSUE THREAD

**Issue by zhaotianye** [RiotGames/leaguedirector#4]
When I start League Director, I can only see a blank checkbox without any option. I'm in China and I'm using Windows 10.

**Comment by zhaotianye** [comment]
The software interface is like this: [https://services.myendnoteweb.com/enwservices/fileattachment/downloadAttachment.jsp?fileName=%26%23x56FE%3B%26%23x7247%3B1.png&userId=WK1nzQrYFsoAACggCp8&refId=242&fileNamePlain=%E5%9B%BE%E7%89%871.png&](url)

**Comment by cammm** [comment]
This is only live on the PBE test server in North America for now, it will be available in the 9.4 release.
