### ISSUE TITLE
Does not work on replays launched through command-line

### ISSUE THREAD

**Issue by Ivi104** [RiotGames/leaguedirector#6]
The program does not start if the replay is launched through use of command line arguments.

**Comment by cammm** [comment]
Can you share with me a little more detail? Where is your game installed? What patch version are you trying? (League Director only works on patch 9.4 or later) How are you starting the replay (share the full command line). What exactly isn't working? Does it not list the game in the welcome screen or does just not connect?

Can you try starting the replay up and once loaded go to this url in your browser (skip past the security warning, just a certificate validation thing).

https://127.0.0.1:2999/replay/game/

Go to where you game is installed and find the file: under Config/Game.cfg and look for the following option and make sure it is set to 1 not 0:

`
[General]
EnableReplayApi=1
`

**Comment by Ivi104** [comment]
Sure, I downloaded the replay from [League of Graphs](https://www.leagueofgraphs.com/replays/with-high-kda/brand/iron), and the replay starts normally. (In the link click 'watch', click 'download and run', and start the .bat file.)

League Director shows the correct path to the game, the checkbox is checked, and the patch is 9.4, but it cannot proceed past the connect screen, despite the replay running.

When I try the link above, Chrome gives me ERR_CONNECTION_REFUSED error.

The game config option is set correctly.

**Comment by cammm** [comment]
The replay API only works with ROFL files, not the hosted replays that league of graphs is using. If you can download a ROFL file directly and run that you should be ok.
